Document: ochi
Title: Debian ochi Manual
Author: <insert document author here>
Abstract: This manual describes what ochi is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ochi/ochi.sgml.gz

Format: postscript
Files: /usr/share/doc/ochi/ochi.ps.gz

Format: text
Files: /usr/share/doc/ochi/ochi.text.gz

Format: HTML
Index: /usr/share/doc/ochi/html/index.html
Files: /usr/share/doc/ochi/html/*.html
