#include<stdio.h>

void main(){

printf("Training file for ochi\n");
printf("File automatically generated by ochi_prepare_train_file on date\n\n");
printf("entwidth = 32\n");
printf("entheight = 32\n");
printf("depth = 1\n");
printf("density = 300\n");
printf("whitepix = 0\n");
printf("ntot = 1934\n");
printf("ndigit = 1934\n");
printf("nlower = 0\nnupper = 0\nnparag = 0\nfirstdigit = 0\nlastdigit = 0\n");
printf("firstlower = 0\nlastlower = 0\nfirstupper = 0\nlastupper = 0\n");
printf("firstparag = 0\nlastparag = 0\n");


}
