#include<stdio.h>
#include<leptonica/allheaders.h>
#include <glob.h>

glob_t *list_files(int scan_dir);
PIX *loadimage(char *filename);


int main(){

	int i,j,k, n,pixl;
	PIX *pixs;
	glob_t *flist;
for(n=0;n<10;n++){
	flist=list_files(0);
    if(flist->gl_pathc==0) {
        fprintf(stderr,"No files in directory %d... Exiting...\n",n);
        exit(1);
    }



	for(i=0;i<flist->gl_pathc;i++){
		pixs=loadimage(flist->gl_pathv[i]);
		if(pixs==NULL){
            		fprintf(stderr,"Pix error... Exiting...\n");
			exit(1);
		}
 		for(j=0;j<pixGetHeight(pixs);j++){
        		for(k=0;k<pixGetWidth(pixs);k++){
            			pixGetPixel(pixs,k,j,&pixl);
            			printf("%d ",pixl); /* funny transformation of rows/columns. TODO: works with intels, but others??? */
        		}
				printf("\n");
    		}
		printf("TODO\n");

	}
	globfree(flist);
	free(flist);
}
	return (0);
}


glob_t *list_files(int scan_dir){
    int retval;
    char path[1024];
    sprintf(path,"/tmp/%d/*.png", scan_dir);
    glob_t *data=(glob_t *)malloc(sizeof(glob_t));
    retval= glob(path, 0, NULL, data );
    return data;
}

PIX *loadimage(char *filename){
    PIX *pix;
    if ((pix = pixRead(filename)) == NULL) return NULL;
    return pix; 
}


void insert_header(){

printf("Training file for ochi\n");
printf("File automatically generated by ochi_prepare_train_file on date\n\n");
printf("entwidth = 32\n");
printf("entheight = 32\n");
printf("depth = 1\n");
printf("density = 300\n");
printf("whitepix = 0\n");
printf("ntot = 1934\n");
printf("ndigit = 1934\n");
printf("nlower = 0\nnupper = 0\nnparag = 0\nfirstdigit = 0\nlastdigit = 0\n");
printf("firstlower = 0\nlastlower = 0\nfirstupper = 0\nlastupper = 0\n");
printf("firstparag = 0\nlastparag = 0\n");



}
