#include<stdio.h>
#include<stdlib.h>
#include<leptonica/allheaders.h>
#include <glob.h>

glob_t *list_files(int scan_dir);
PIX *loadimage(char *filename);
void insert_header(FILE *file,int i);


int main(){

	int i,j,k, n,pixl, count=0;
	PIX *pixs;
	glob_t *flist;
    FILE *file=fopen("train_file.trn","w");
for(n=0;n<10;n++){
	flist=list_files(n);
    if(flist->gl_pathc==0) {
        fprintf(stderr,"No files in directory %d... Exiting...\n",n);
        exit(1);
    }



	for(i=0;i<flist->gl_pathc;i++){
		pixs=loadimage(flist->gl_pathv[i]);
		if(pixs==NULL){
            		fprintf(stderr,"Pix error... Exiting...\n");
			exit(1);
		}
 		for(j=0;j<pixGetHeight(pixs);j++){
        		for(k=0;k<pixGetWidth(pixs);k++){
            			pixGetPixel(pixs,k,j,&pixl);
            			fprintf(file,"%d",pixl); /* funny transformation of rows/columns. TODO: works with intels, but others??? */
        		}
				fprintf(file,"\n");
    		}
        count++;
		fprintf(file," %d\n",n);

	}
	globfree(flist);
	free(flist);
}
    fclose(file);
//    *file=fopen("train_file.trn","r");
    FILE *file1=fopen("train_file_header.trn","w");
    insert_header(file1,count);
    fclose(file1);
	return (0);
    
}


glob_t *list_files(int scan_dir){
    int retval;
    char path[1024];
    sprintf(path,"/tmp/numerals/%d/*.png", scan_dir);
    glob_t *data=(glob_t *)malloc(sizeof(glob_t));
    retval= glob(path, 0, NULL, data );
    return data;
}

PIX *loadimage(char *filename){
    PIX *pix;
    if ((pix = pixRead(filename)) == NULL) return NULL;
    return pix; 
}


void insert_header(FILE *file,int i){

fprintf(file,"Training file for ochi\n");
fprintf(file,"File automatically generated by ochi_prepare_train_file on date\n\n");
fprintf(file,"entwidth = 32\n");
fprintf(file,"entheight = 32\n");
fprintf(file,"depth = 1\n");
fprintf(file,"density = 300\n");
fprintf(file,"whitepix = 0\n");
fprintf(file,"ntot = %d\n",i);
fprintf(file,"ndigit = %d\n",i);
fprintf(file,"nlower = 0\nnupper = 0\nnparag = 0\nfirstdigit = 0\nlastdigit = 0\n");
fprintf(file,"firstlower = 0\nlastlower = 0\nfirstupper = 0\nlastupper = 0\n");
fprintf(file,"firstparag = 0\nlastparag = 0\n");

}
